# Generated by Django 2.1.1 on 2018-09-20 14:39

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Stol',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.IntegerField(default=1)),
                ('quantity', models.IntegerField(default=1)),
                ('forma', models.CharField(default='square', max_length=20)),
                ('x_cord', models.IntegerField(default=1)),
                ('y_cord', models.IntegerField(default=1)),
                ('len_stol', models.FloatField(default=1)),
                ('width_stol', models.FloatField(default=1)),
                ('reserved', models.BooleanField(default=False)),
                ('begin_res', models.DateField(blank=True, null=True)),
                ('end_res', models.DateField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'Stol',
                'verbose_name_plural': 'Stoliki',
            },
        ),
    ]
