# Generated by Django 2.1.1 on 2018-09-21 08:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Zakaz', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CurrentDate',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(verbose_name='Дата')),
            ],
            options={
                'verbose_name': 'Текущая дата',
            },
        ),
        migrations.RenameField(
            model_name='stol',
            old_name='begin_res',
            new_name='time_res',
        ),
        migrations.RemoveField(
            model_name='stol',
            name='end_res',
        ),
    ]
