# Generated by Django 2.1.1 on 2018-09-22 10:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Zakaz', '0002_auto_20180921_1135'),
    ]

    operations = [
        migrations.CreateModel(
            name='MonthJournal',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(verbose_name='Дата')),
                ('present_day1', models.BooleanField(default=False)),
                ('present_day2', models.BooleanField(default=False)),
                ('present_day3', models.BooleanField(default=False)),
                ('present_day4', models.BooleanField(default=False)),
                ('present_day5', models.BooleanField(default=False)),
                ('present_day6', models.BooleanField(default=False)),
                ('present_day7', models.BooleanField(default=False)),
                ('present_day8', models.BooleanField(default=False)),
                ('present_day9', models.BooleanField(default=False)),
                ('present_day10', models.BooleanField(default=False)),
                ('present_day11', models.BooleanField(default=False)),
                ('present_day12', models.BooleanField(default=False)),
                ('present_day13', models.BooleanField(default=False)),
                ('present_day14', models.BooleanField(default=False)),
                ('present_day15', models.BooleanField(default=False)),
            ],
            options={
                'verbose_name': 'Місячний Журнал',
                'verbose_name_plural': 'Місячні Журнали',
            },
        ),
        migrations.RemoveField(
            model_name='stol',
            name='time_res',
        ),
        migrations.AddField(
            model_name='monthjournal',
            name='stol',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Zakaz.Stol', verbose_name='Stol'),
        ),
    ]
