# Generated by Django 2.1.1 on 2018-09-22 10:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Zakaz', '0003_auto_20180922_1303'),
    ]

    operations = [
        migrations.AlterField(
            model_name='monthjournal',
            name='stol',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Zakaz.Stol', unique_for_month='date', verbose_name='Stol'),
        ),
    ]
