# Generated by Django 2.1.1 on 2018-09-22 10:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Zakaz', '0005_auto_20180922_1320'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='monthjournal',
            name='present_day1',
        ),
        migrations.RemoveField(
            model_name='monthjournal',
            name='present_day10',
        ),
        migrations.RemoveField(
            model_name='monthjournal',
            name='present_day11',
        ),
        migrations.RemoveField(
            model_name='monthjournal',
            name='present_day12',
        ),
        migrations.RemoveField(
            model_name='monthjournal',
            name='present_day13',
        ),
        migrations.RemoveField(
            model_name='monthjournal',
            name='present_day14',
        ),
        migrations.RemoveField(
            model_name='monthjournal',
            name='present_day15',
        ),
        migrations.RemoveField(
            model_name='monthjournal',
            name='present_day2',
        ),
        migrations.RemoveField(
            model_name='monthjournal',
            name='present_day3',
        ),
        migrations.RemoveField(
            model_name='monthjournal',
            name='present_day4',
        ),
        migrations.RemoveField(
            model_name='monthjournal',
            name='present_day5',
        ),
        migrations.RemoveField(
            model_name='monthjournal',
            name='present_day6',
        ),
        migrations.RemoveField(
            model_name='monthjournal',
            name='present_day7',
        ),
        migrations.RemoveField(
            model_name='monthjournal',
            name='present_day8',
        ),
        migrations.RemoveField(
            model_name='monthjournal',
            name='present_day9',
        ),
    ]
